import type {
  AdminStats,
  Company,
  Worker,
  Notification,
  AbsenceAlert,
  Inquiry,
  DailyAttendanceData,
  MonthlyWorkStats,
} from '@/types/adminDashboard';
import type { NoteUpdateAlert } from '../_components/NoteUpdateAlertList';

export const adminStats: AdminStats = {
  totalCompanies: 24,
  totalWorkers: 156,
  activeWorkers: 142,
  attendanceRate: 94.5,
  expiringContracts: 5,
  pendingIssues: 14,
  monthlyRevenue: 45600000,
  newInquiries: 8,
  pendingConsultations: 5,
};

export const companiesData: Company[] = [
  {
    id: 1,
    name: '(주)두루빛 제조',
    industry: '제조업',
    location: '서울 강남구',
    workers: 15,
    contractEnd: '2026-12-31',
    status: 'active',
    revenue: 4500000,
    pm: { name: '김영업', phone: '010-1111-2222', email: 'sales.kim@duruviter.com' },
  },
  {
    id: 2,
    name: '세종식품',
    industry: '식품가공',
    location: '경기 성남시',
    workers: 12,
    contractEnd: '2026-03-15',
    status: 'expiring',
    revenue: 3600000,
    pm: { name: '이매니저', phone: '010-5555-6666', email: 'manager.lee@duruviter.com' },
  },
  {
    id: 3,
    name: '한빛포장',
    industry: '포장/물류',
    location: '인천 남동구',
    workers: 18,
    contractEnd: '2027-06-30',
    status: 'active',
    revenue: 5400000,
    pm: { name: '최영업', phone: '010-7777-8888', email: 'sales.choi@duruviter.com' },
  },
  {
    id: 4,
    name: '그린팜',
    industry: '농업',
    location: '충남 천안시',
    workers: 8,
    contractEnd: '2026-02-28',
    status: 'expiring',
    revenue: 2400000,
    pm: { name: '정담당', phone: '010-9999-0000', email: 'pm.jung@duruviter.com' },
  },
  {
    id: 5,
    name: '참좋은케어',
    industry: '서비스업',
    location: '서울 송파구',
    workers: 10,
    contractEnd: '2026-09-15',
    status: 'active',
    revenue: 3000000,
    pm: { name: '한영업', phone: '010-1234-5678', email: 'sales.han@duruviter.com' },
  },
];

export const workersData: Worker[] = [
  {
    id: 1,
    name: '김민수',
    company: '(주)두루빛 제조',
    department: '제조부',
    disabilityType: '지체장애',
    status: 'working',
    phone: '010-1234-5678',
    contractEnd: '2026-12-31',
    workerId: 'ms0315',
    notes: '성실하고 꼼꼼함. 품질 검수 업무에 적합',
    isResigned: false,
    isWaiting: false,
    resignDate: null,
    resignReason: null,
  },
  {
    id: 2,
    name: '이영희',
    company: '(주)두루빛 제조',
    department: '포장부',
    disabilityType: '청각장애',
    status: 'working',
    phone: '010-2345-6789',
    contractEnd: '2026-12-31',
    workerId: 'yh0520',
    notes: '수화 가능. 포장 작업 숙련도 높음',
    isResigned: false,
    isWaiting: false,
    resignDate: null,
    resignReason: null,
  },
  {
    id: 3,
    name: '박철수',
    company: '세종식품',
    department: '생산부',
    disabilityType: '시각장애',
    status: 'working',
    phone: '010-3456-7890',
    contractEnd: '2026-03-15',
    workerId: 'cs1108',
    notes: '보조기기 사용. 단순 조립 업무 담당',
    isResigned: false,
    isWaiting: false,
    resignDate: null,
    resignReason: null,
  },
  {
    id: 4,
    name: '정미라',
    company: '한빛포장',
    department: '품질관리',
    disabilityType: '지체장애',
    status: 'working',
    phone: '010-4567-8901',
    contractEnd: '2027-06-30',
    workerId: 'mr0723',
    notes: '휠체어 사용. 사무 보조 업무 가능',
    isResigned: false,
    isWaiting: false,
    resignDate: null,
    resignReason: null,
  },
  {
    id: 5,
    name: '최동욱',
    company: '그린팜',
    department: '재배',
    disabilityType: '발달장애',
    status: 'resigned',
    phone: '010-5678-9012',
    contractEnd: '2026-02-28',
    workerId: 'dw0412',
    notes: '반복 작업 능숙. 재배 작업 담당했음',
    isResigned: true,
    isWaiting: false,
    resignDate: '2026-01-22',
    resignReason: '개인 사유로 인한 자진 퇴사',
  },
  {
    id: 6,
    name: '한지민',
    company: '세종식품',
    department: '포장부',
    disabilityType: '청각장애',
    status: 'resigned',
    phone: '010-6789-0123',
    contractEnd: '2026-06-30',
    workerId: 'jm0630',
    notes: '수화 의사소통. 꼼꼼한 성격',
    isResigned: true,
    isWaiting: false,
    resignDate: '2026-01-15',
    resignReason: '건강 문제로 인한 퇴사',
  },
];

export const notifications: Notification[] = [
  {
    id: 1,
    type: 'contract',
    title: '세종식품 계약 만료 임박',
    message: '2026년 3월 15일 계약 만료 예정',
    priority: 'high',
    date: '2026-01-28',
  },
  {
    id: 2,
    type: 'document',
    title: '김민수 건강검진 만료',
    message: '건강검진 갱신 필요 (만료: 2026-02-10)',
    priority: 'medium',
    date: '2026-01-27',
  },
  {
    id: 3,
    type: 'attendance',
    title: '최동욱 장기 결근',
    message: '3일 연속 결근, 연락 필요',
    priority: 'high',
    date: '2026-01-26',
  },
  {
    id: 4,
    type: 'payment',
    title: '한빛포장 1월 정산 완료',
    message: '정산 금액: ₩5,400,000',
    priority: 'low',
    date: '2026-01-25',
  },
];

export const absenceAlerts: AbsenceAlert[] = [
  { id: 1, name: '최동욱', company: '그린팜', date: '2026-02-10', status: '결근' },
  { id: 2, name: '정미라', company: '한빛포장', date: '2026-02-10', status: '결근' },
  { id: 3, name: '박철수', company: '세종식품', date: '2026-02-10', status: '지각' },
  { id: 4, name: '김수진', company: '(주)두루빛 제조', date: '2026-02-09', status: '결근' },
  { id: 5, name: '이민호', company: '세종식품', date: '2026-02-09', status: '결근' },
  { id: 6, name: '박지영', company: '한빛포장', date: '2026-02-09', status: '지각' },
  { id: 7, name: '강태민', company: '그린팜', date: '2026-02-08', status: '결근' },
  { id: 8, name: '윤서아', company: '그린팜', date: '2026-02-08', status: '결근' },
  { id: 9, name: '이준호', company: '한빛포장', date: '2026-02-08', status: '지각' },
  { id: 10, name: '김하은', company: '한빛포장', date: '2026-02-07', status: '결근' },
  { id: 11, name: '박서준', company: '(주)두루빛 제조', date: '2026-02-07', status: '결근' },
  { id: 12, name: '최민지', company: '세종식품', date: '2026-02-07', status: '지각' },
  { id: 13, name: '정민아', company: '(주)두루빛 제조', date: '2026-02-06', status: '결근' },
  { id: 14, name: '박영수', company: '(주)두루빛 제조', date: '2026-02-06', status: '결근' },
  { id: 15, name: '최지현', company: '(주)두루빛 제조', date: '2026-02-05', status: '지각' },
];

export const inquiryList: Inquiry[] = [
  {
    id: 1,
    company: '(주)삼성전자',
    ceo: '홍길동',
    date: '2026-01-30',
    phone: '02-1234-5678',
    email: 'hong@samsung.com',
    summary: '장애인 고용 관련 상담을 받고 싶습니다.',
    content:
      '현재 장애인 고용 의무 비율 관련하여 채용 및 관리 프로세스 상담을 받고 싶습니다. 특히 제조 현장에 적합한 직무 배치 방안이 궁금합니다.',
  },
  {
    id: 2,
    company: '(주)현대자동차',
    ceo: '김철수',
    date: '2026-01-29',
    phone: '02-2345-6789',
    email: 'kim@hyundai.com',
    summary: '파견 근로자 배치 문의드립니다.',
    content:
      '울산 공장 내 경포장 라인에 장애인 근로자 파견을 검토하고 있습니다. 가능한 인원과 절차가 궁금합니다.',
  },
  {
    id: 3,
    company: '(주)LG전자',
    ceo: '박영희',
    date: '2026-01-28',
    phone: '02-3456-7890',
    email: 'park@lg.com',
    summary: '고용 장려금 컨설팅 요청합니다.',
    content:
      '장애인 고용 장려금 신청 절차와 이루빛터 서비스 연계 방안에 대해 상세히 알고 싶습니다.',
  },
  {
    id: 4,
    company: '(주)CJ대한통운',
    ceo: '이정호',
    date: '2026-01-27',
    phone: '02-4567-8901',
    email: 'lee@cj.com',
    summary: '물류센터 인력 배치 상담 요청합니다.',
    content:
      '경기도 이천 물류센터에 단순 분류 작업이 가능한 장애인 근로자 배치를 희망합니다.',
  },
  {
    id: 5,
    company: '(주)아모레퍼시픽',
    ceo: '서민지',
    date: '2026-01-26',
    phone: '02-5678-9012',
    email: 'seo@amore.com',
    summary: '사회공헌 연계 고용 프로그램 문의합니다.',
    content:
      'ESG 경영 차원에서 장애인 고용과 연계한 사회공헌 프로그램을 기획 중입니다. 협업 가능 여부를 확인하고 싶습니다.',
  },
  {
    id: 6,
    company: '(주)롯데마트',
    ceo: '한상우',
    date: '2026-01-25',
    phone: '02-6789-0123',
    email: 'han@lotte.com',
    summary: '매장 내 직무 배치 가능 여부가 궁금합니다.',
    content:
      '서울 시내 매장에 장애인 근로자를 배치할 수 있는 직무가 있는지 상담받고 싶습니다.',
  },
];

export const dailyAttendance: DailyAttendanceData = {
  '(주)두루빛 제조': {
    morning: [
      { id: 1, name: '김민수', department: '제조부', checkin: '09:00', checkout: '-', workContent: '', needsAttention: false, phone: '010-1234-5678' },
      { id: 2, name: '이영희', department: '포장부', checkin: '09:05', checkout: '-', workContent: '', needsAttention: false, phone: '010-2345-6789' },
    ],
    afternoon: [
      { id: 7, name: '김수진', department: '제조부', checkin: '14:00', checkout: '-', workContent: '', needsAttention: false, phone: '010-7777-1234' },
      { id: 11, name: '박서준', department: '포장부', checkin: '14:05', checkout: '-', workContent: '', needsAttention: false, phone: '010-1111-2222' },
    ],
  },
  '세종식품': {
    morning: [
      { id: 3, name: '박철수', department: '생산부', checkin: '09:00', checkout: '-', workContent: '', needsAttention: false, phone: '010-3456-7890' },
      { id: 8, name: '이민호', department: '생산부', checkin: '-', checkout: '-', workContent: '', needsAttention: true, phone: '010-8888-3333' },
    ],
    afternoon: [
      { id: 12, name: '최민지', department: '생산부', checkin: '13:00', checkout: '-', workContent: '', needsAttention: false, phone: '010-1212-3434' },
    ],
  },
  '한빛포장': {
    morning: [
      { id: 4, name: '정미라', department: '품질관리', checkin: '09:10', checkout: '-', workContent: '', needsAttention: true, phone: '010-4567-8901' },
      { id: 9, name: '박지영', department: '포장부', checkin: '09:00', checkout: '-', workContent: '', needsAttention: false, phone: '010-9999-4444' },
    ],
    afternoon: [
      { id: 13, name: '이준호', department: '포장부', checkin: '14:00', checkout: '-', workContent: '', needsAttention: false, phone: '010-1313-5656' },
      { id: 14, name: '김하은', department: '품질관리', checkin: '14:10', checkout: '-', workContent: '', needsAttention: false, phone: '010-1414-7878' },
    ],
  },
  '그린팜': {
    morning: [
      { id: 5, name: '최동욱', department: '재배', checkin: '-', checkout: '-', workContent: '', needsAttention: true, phone: '010-5678-9012' },
      { id: 10, name: '강태민', department: '재배', checkin: '09:00', checkout: '-', workContent: '', needsAttention: false, phone: '010-1010-5555' },
    ],
    afternoon: [
      { id: 15, name: '윤서아', department: '재배', checkin: '13:30', checkout: '-', workContent: '', needsAttention: false, phone: '010-1515-9090' },
    ],
  },
};

export const monthlyWorkStats: MonthlyWorkStats = {
  '(주)두루빛 제조': [
    { id: 1, name: '김민수', department: '제조부', totalHours: 176, avgHours: 8.0, workDays: 22, lateDays: 0, scheduledWorkDays: ['월', '화', '수', '목', '금'] },
    { id: 2, name: '이영희', department: '포장부', totalHours: 168, avgHours: 7.6, workDays: 22, lateDays: 1, scheduledWorkDays: ['월', '화', '수', '목', '금'] },
    { id: 7, name: '김수진', department: '제조부', totalHours: 172, avgHours: 7.8, workDays: 22, lateDays: 0, scheduledWorkDays: ['월', '화', '수', '목', '금'] },
    { id: 16, name: '박영수', department: '포장부', totalHours: 180, avgHours: 8.2, workDays: 22, lateDays: 0, scheduledWorkDays: ['월', '화', '수', '목', '금'] },
    { id: 17, name: '최지현', department: '제조부', totalHours: 170, avgHours: 7.7, workDays: 22, lateDays: 1, scheduledWorkDays: ['월', '화', '목', '금'] },
    { id: 18, name: '정민아', department: '품질관리', totalHours: 176, avgHours: 8.0, workDays: 22, lateDays: 0, scheduledWorkDays: ['월', '화', '수', '목', '금'] },
  ],
  '세종식품': [
    { id: 3, name: '박철수', department: '생산부', totalHours: 180, avgHours: 8.2, workDays: 22, lateDays: 0, scheduledWorkDays: ['월', '화', '수', '목', '금'] },
    { id: 8, name: '이민호', department: '생산부', totalHours: 160, avgHours: 7.3, workDays: 22, lateDays: 3, scheduledWorkDays: ['화', '수', '목'] },
  ],
  '한빛포장': [
    { id: 4, name: '정미라', department: '품질관리', totalHours: 176, avgHours: 8.0, workDays: 22, lateDays: 2, scheduledWorkDays: ['월', '화', '수', '목', '금'] },
    { id: 9, name: '박지영', department: '포장부', totalHours: 175, avgHours: 8.0, workDays: 22, lateDays: 0, scheduledWorkDays: ['월', '수', '금'] },
  ],
  '그린팜': [
    { id: 5, name: '최동욱', department: '재배', totalHours: 140, avgHours: 6.4, workDays: 22, lateDays: 5, scheduledWorkDays: ['월', '화', '수'] },
    { id: 10, name: '강태민', department: '재배', totalHours: 176, avgHours: 8.0, workDays: 22, lateDays: 0, scheduledWorkDays: ['월', '화', '수', '목', '금'] },
  ],
};

export const noteUpdateAlerts: NoteUpdateAlert[] = [
  {
    id: 1,
    workerName: '김민수',
    companyName: '(주)두루빛 제조',
    noteContent: '최근 컨디션이 좋지 않아 보임. 점심시간 이후 피로감 호소. 휴식 시간 추가 배려 필요. 담당 의사와 상담 예정.',
    updatedAt: '2026-01-28 14:30',
  },
  {
    id: 2,
    workerName: '이영희',
    companyName: '세종식품',
    noteContent: '업무 적응도 우수. 포장 작업 속도 향상됨. 다음 주부터 새로운 작업 라인 배치 검토 중.',
    updatedAt: '2026-01-28 11:15',
  },
  {
    id: 3,
    workerName: '박철수',
    companyName: '한빛포장',
    noteContent: '가족 상황으로 인해 근무 시간 조정 요청. 오전 근무만 희망. 인사팀과 협의 필요.',
    updatedAt: '2026-01-27 16:45',
  },
];
