import type { Employee } from '@/types/employee';
import type {
  SentNotice,
  AddWorkerForm,
} from '@/types/companyDashboard';

// 더미 데이터
export const initialEmployees: Employee[] = [
  {
    id: '1',
    name: '김민수',
    phone: '010-1234-5678',
    disability: '지체장애 경증',
    hireDate: '2025-03-01',
    gender: '남',
    emergencyContactName: null,
    emergencyContactRelation: null,
    emergencyContactPhone: null,
    status: 'checkin',
    checkinTime: '09:00',
    checkoutTime: null,
    uniqueCode: 'ms0315',
    companyNote: '성실하고 꼼꼼함. 품질 검수 업무에 적합',
    isActive: true,
    resignDate: null,
    resignReason: null,
    workDays: [1, 2, 3, 4, 5],
    workStartTime: '09:00',
    disabilityType: '지체장애',
    disabilitySeverity: '경증',
    disabilityRecognitionDate: '2020-03-15',
  },
  {
    id: '2',
    name: '이영희',
    phone: '010-2345-6789',
    disability: '청각장애 중증',
    hireDate: '2025-06-15',
    gender: '여',
    emergencyContactName: null,
    emergencyContactRelation: null,
    emergencyContactPhone: null,
    status: 'checkin',
    checkinTime: '09:15',
    checkoutTime: null,
    uniqueCode: 'yh0520',
    companyNote: '수화 가능. 포장 작업 숙련도 높음',
    isActive: true,
    resignDate: null,
    resignReason: null,
    workDays: [1, 2, 3, 4, 5],
    workStartTime: '09:00',
    disabilityType: '청각장애',
    disabilitySeverity: '중증',
    disabilityRecognitionDate: '2019-08-20',
  },
  {
    id: '3',
    name: '박철수',
    phone: '010-3456-7890',
    disability: '시각장애 경증',
    hireDate: '2025-08-01',
    gender: '남',
    emergencyContactName: null,
    emergencyContactRelation: null,
    emergencyContactPhone: null,
    status: 'checkout',
    checkinTime: '09:00',
    checkoutTime: '18:00',
    uniqueCode: 'cs1108',
    companyNote: '보조기기 사용. 단순 조립 업무 담당',
    isActive: true,
    resignDate: null,
    resignReason: null,
    workDays: [1, 2, 3, 4, 5],
    workStartTime: '09:00',
    disabilityType: '시각장애',
    disabilitySeverity: '경증',
    disabilityRecognitionDate: '2021-05-10',
  },
  {
    id: '4',
    name: '정미라',
    phone: '010-4567-8901',
    disability: '지체장애 중증',
    hireDate: '2025-09-01',
    gender: '여',
    emergencyContactName: null,
    emergencyContactRelation: null,
    emergencyContactPhone: null,
    status: 'checkin',
    checkinTime: '08:45',
    checkoutTime: null,
    uniqueCode: 'mr0723',
    companyNote: '휠체어 사용. 사무 보조 업무 가능',
    isActive: true,
    resignDate: null,
    resignReason: null,
    workDays: [1, 2, 3, 4, 5],
    workStartTime: '09:00',
    disabilityType: '지체장애',
    disabilitySeverity: '중증',
    disabilityRecognitionDate: '2018-11-25',
  },
  {
    id: '5',
    name: '최동욱',
    phone: '010-5678-9012',
    disability: '발달장애 경증',
    hireDate: '2025-11-01',
    gender: '남',
    emergencyContactName: null,
    emergencyContactRelation: null,
    emergencyContactPhone: null,
    status: 'resigned',
    checkinTime: null,
    checkoutTime: null,
    uniqueCode: 'dw0412',
    companyNote: '반복 작업 능숙. 재배 작업 담당했음',
    isActive: false,
    resignDate: '2026-01-22',
    resignReason: '개인 사유로 인한 자진 퇴사',
    workDays: [1, 2, 3, 4, 5],
    workStartTime: '09:00',
    disabilityType: '지적장애',
    disabilitySeverity: '경증',
    disabilityRecognitionDate: '2022-01-08',
  },
];

export const initialNotices: SentNotice[] = [
  {
    id: 1,
    date: '2026-01-28 14:30',
    workers: ['김민수', '이영희', '박철수', '정미라', '최동욱'],
    content: '내일 오전 10시에 안전교육이 진행됩니다.\n필히 참석 부탁드립니다.',
    sender: '관리자',
  },
  {
    id: 2,
    date: '2026-01-25 09:00',
    workers: ['김민수', '이영희'],
    content: '금일 제조부 근무시간이 1시간 연장됩니다.',
    sender: '관리자',
  },
];

export const INITIAL_ADD_WORKER_FORM: AddWorkerForm = {
  name: '',
  ssn: '',
  phone: '',
  gender: '',
  emergencyName: '',
  emergencyRelation: '',
  emergencyPhone: '',
  disabilityType: '',
  disabilitySeverity: '',
  hireDate: '',
  recognitionDate: '',
  workDays: [],
  workStartTime: '',
  workerId: '',
};
